[2024-08-19 09:41:21.345792] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:47:21.921433] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:47:22.286159] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:47:22.486034] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:47:22.675744] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:47:22.794617] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:47:22.998142] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:49:06.733924] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:49:06.949776] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:49:07.088544] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:49:07.342040] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 09:49:07.462770] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 17:49:23.966609] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 17:49:24.164300] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 17:49:24.414381] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 17:49:24.615182] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 17:49:24.836214] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 17:49:24.981981] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 17:58:17.904588] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 17:58:19.707691] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 18:04:22.177943] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 19:02:11.314213] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 19:02:13.074789] INFO: hello world专用: 有人访问你的网站了
[2024-08-19 20:07:19.000267] INFO: UserDao: 有人访问你的网站了
[2024-08-19 20:07:19.355921] INFO: UserDao: 有人访问你的网站了
[2024-08-19 20:07:19.602647] INFO: UserDao: 有人访问你的网站了
[2024-08-19 20:07:19.803450] INFO: UserDao: 有人访问你的网站了
[2024-08-19 20:07:20.094559] INFO: UserDao: 有人访问你的网站了
[2024-08-19 20:07:20.315951] INFO: UserDao: 有人访问你的网站了
[2024-08-19 20:07:40.735924] INFO: UserDao: 有人访问你的网站了
[2024-08-19 20:22:17.383449] ERROR: UserDao: 用户注册失败: 用户名或邮箱已存在
[2024-08-19 20:22:34.524000] ERROR: UserDao: 用户注册失败: 用户名或邮箱已存在
[2024-08-19 20:22:45.420494] ERROR: UserDao: 用户注册失败: 用户名或邮箱已存在
[2024-08-19 20:27:56.224145] ERROR: UserDao: 用户注册失败: Unicode-objects must be encoded before hashing
[2024-08-19 20:31:11.662985] ERROR: UserDao: 用户注册失败: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO user (username, name, password, email, `role`, created_at, updated_at, deleted_at, last_login_at) VALUES (%(username)s, %(name)s, %(password)s, %(email)s, %(role)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(last_login_at)s)]
[parameters: {'username': '311123', 'name': 'zhan122122121221zhan', 'password': 'dc92c34a5ff7473b166c1bad26fd9b7c', 'email': '12zhan111310@164.com', 'role': 0, 'created_at': datetime.datetime(2024, 8, 19, 20, 31, 11, 656864), 'updated_at': datetime.datetime(2024, 8, 19, 20, 31, 11, 656872), 'deleted_at': None, 'last_login_at': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
[2024-08-19 20:31:31.695045] ERROR: UserDao: 用户注册失败: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO user (username, name, password, email, `role`, created_at, updated_at, deleted_at, last_login_at) VALUES (%(username)s, %(name)s, %(password)s, %(email)s, %(role)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(last_login_at)s)]
[parameters: {'username': '311', 'name': 'zhan122122121221zhan', 'password': '92152227466766749d9d9da31c41ac1c', 'email': '12zhan111310@164.com', 'role': 0, 'created_at': datetime.datetime(2024, 8, 19, 20, 31, 31, 693796), 'updated_at': datetime.datetime(2024, 8, 19, 20, 31, 31, 693804), 'deleted_at': None, 'last_login_at': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
[2024-08-19 20:31:42.124504] ERROR: UserDao: 用户注册失败: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO user (username, name, password, email, `role`, created_at, updated_at, deleted_at, last_login_at) VALUES (%(username)s, %(name)s, %(password)s, %(email)s, %(role)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(last_login_at)s)]
[parameters: {'username': '311', 'name': 'zhan122122121221zhan', 'password': '92152227466766749d9d9da31c41ac1c', 'email': '12zhan10@164.com', 'role': 0, 'created_at': datetime.datetime(2024, 8, 19, 20, 31, 42, 123402), 'updated_at': datetime.datetime(2024, 8, 19, 20, 31, 42, 123410), 'deleted_at': None, 'last_login_at': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
[2024-08-20 02:42:07.762287] INFO: UserDao: 有人访问你的网站了
[2024-08-20 02:42:07.985661] INFO: UserDao: 有人访问你的网站了
[2024-08-20 02:42:08.220734] INFO: UserDao: 有人访问你的网站了
[2024-08-20 02:42:08.388335] INFO: UserDao: 有人访问你的网站了
[2024-08-20 15:42:14.418832] ERROR: UserDao: 用户注册失败: 用户名或邮箱已存在
[2024-08-20 15:48:15.253659] ERROR: UserDao: 用户注册失败: 用户名或邮箱已存在
[2024-08-21 13:43:53.027508] INFO: UserDao: 有人访问你的网站了
[2024-08-24 03:03:01.693215] ERROR: UserDao: 获取用户: 0项目列表失败, list_project_by_user() missing 1 required positional argument: 'user_id'
[2024-08-24 03:06:20.416600] ERROR: UserDao: 获取用户: 0项目列表失败, list_project_by_user() missing 1 required positional argument: 'user_id'
[2024-08-24 03:10:44.165281] ERROR: UserDao: 获取用户: 0项目列表失败, list_project_by_user() missing 1 required positional argument: 'user_id'
[2024-08-24 03:13:19.714729] ERROR: UserDao: 获取用户: 0项目列表失败, list_project_by_user() missing 1 required positional argument: 'user_id'
[2024-08-24 03:13:20.561534] ERROR: UserDao: 获取用户: 0项目列表失败, list_project_by_user() missing 1 required positional argument: 'user_id'
[2024-08-24 03:13:21.623940] ERROR: UserDao: 获取用户: 0项目列表失败, list_project_by_user() missing 1 required positional argument: 'user_id'
[2024-08-24 03:13:22.545014] ERROR: UserDao: 获取用户: 0项目列表失败, list_project_by_user() missing 1 required positional argument: 'user_id'
[2024-08-24 03:25:39.254617] ERROR: UserDao: 获取用户: 0项目列表失败, list_project_by_user() missing 1 required positional argument: 'user_id'
[2024-08-24 03:33:36.898601] ERROR: UserDao: 获取用户: 13项目列表失败, list_project_by_user() missing 1 required positional argument: 'user_id'
[2024-08-24 03:38:55.452640] ERROR: UserDao: 获取用户: 13项目列表失败, list_project_by_user() missing 1 required positional argument: 'user_id'
[2024-08-24 03:39:14.646373] ERROR: UserDao: 查询用户：13项目失败，Entity namespace for "project_role" has no property "user_id"
[2024-08-24 03:39:14.646768] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 03:40:48.386173] ERROR: UserDao: 查询用户：13项目失败，Entity namespace for "project_role" has no property "user_id"
[2024-08-24 03:41:14.565678] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 03:59:56.544307] ERROR: UserDao: 查询用户：13项目失败，Entity namespace for "project_role" has no property "user_id"
[2024-08-24 03:59:56.544550] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 03:59:58.369456] ERROR: UserDao: 查询用户：13项目失败，Entity namespace for "project_role" has no property "user_id"
[2024-08-24 03:59:58.369586] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 03:59:59.606742] ERROR: UserDao: 查询用户：13项目失败，Entity namespace for "project_role" has no property "user_id"
[2024-08-24 03:59:59.606881] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 04:00:33.374247] ERROR: UserDao: 查询用户：13项目失败，Entity namespace for "project_role" has no property "user_id"
[2024-08-24 04:00:33.374538] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 04:26:13.096638] ERROR: UserDao: 查询用户：13项目失败，Entity namespace for "project_role" has no property "user_id"
[2024-08-24 04:26:13.099051] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 05:24:06.035199] ERROR: UserDao: 查询用户：13项目失败，Entity namespace for "project_role" has no property "user_id"
[2024-08-24 05:24:06.036610] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 05:38:41.345398] ERROR: UserDao: 查询用户：13项目失败，Entity namespace for "project_role" has no property "user_id"
[2024-08-24 05:39:34.441903] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 06:12:28.020212] ERROR: UserDao: 查询用户：13项目失败，Entity namespace for "project_role" has no property "user_id"
[2024-08-24 06:15:57.116711] ERROR: UserDao: 查询用户：13项目失败，(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project_role.user_id' in 'field list'
[SQL: SELECT project_role.id AS project_role_id, project_role.user_id AS project_role_user_id, project_role.project_id AS project_role_project_id, project_role.project_role AS project_role_project_role, project_role.created_at AS project_role_created_at, project_role.updated_at AS project_role_updated_at, project_role.deleted_at AS project_role_deleted_at, project_role.create_user AS project_role_create_user, project_role.update_user AS project_role_update_user 
FROM project_role 
WHERE project_role.user_id = %(user_id_1)s AND project_role.deleted_at IS NULL]
[parameters: {'user_id_1': 13}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2024-08-24 06:15:57.117012] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 06:15:59.420049] ERROR: UserDao: 查询用户：13项目失败，(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project_role.user_id' in 'field list'
[SQL: SELECT project_role.id AS project_role_id, project_role.user_id AS project_role_user_id, project_role.project_id AS project_role_project_id, project_role.project_role AS project_role_project_role, project_role.created_at AS project_role_created_at, project_role.updated_at AS project_role_updated_at, project_role.deleted_at AS project_role_deleted_at, project_role.create_user AS project_role_create_user, project_role.update_user AS project_role_update_user 
FROM project_role 
WHERE project_role.user_id = %(user_id_1)s AND project_role.deleted_at IS NULL]
[parameters: {'user_id_1': 13}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2024-08-24 06:15:59.420203] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 06:17:50.787209] ERROR: UserDao: 查询用户：13项目失败，(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project_role.user_id' in 'field list'
[SQL: SELECT project_role.id AS project_role_id, project_role.user_id AS project_role_user_id, project_role.project_id AS project_role_project_id, project_role.project_role AS project_role_project_role, project_role.created_at AS project_role_created_at, project_role.updated_at AS project_role_updated_at, project_role.deleted_at AS project_role_deleted_at, project_role.create_user AS project_role_create_user, project_role.update_user AS project_role_update_user 
FROM project_role 
WHERE project_role.user_id = %(user_id_1)s AND project_role.deleted_at IS NULL]
[parameters: {'user_id_1': 13}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2024-08-24 06:17:50.788256] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 06:17:51.192463] ERROR: UserDao: 查询用户：13项目失败，(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project_role.user_id' in 'field list'
[SQL: SELECT project_role.id AS project_role_id, project_role.user_id AS project_role_user_id, project_role.project_id AS project_role_project_id, project_role.project_role AS project_role_project_role, project_role.created_at AS project_role_created_at, project_role.updated_at AS project_role_updated_at, project_role.deleted_at AS project_role_deleted_at, project_role.create_user AS project_role_create_user, project_role.update_user AS project_role_update_user 
FROM project_role 
WHERE project_role.user_id = %(user_id_1)s AND project_role.deleted_at IS NULL]
[parameters: {'user_id_1': 13}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2024-08-24 06:17:51.192703] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 06:17:51.922722] ERROR: UserDao: 查询用户：13项目失败，(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project_role.user_id' in 'field list'
[SQL: SELECT project_role.id AS project_role_id, project_role.user_id AS project_role_user_id, project_role.project_id AS project_role_project_id, project_role.project_role AS project_role_project_role, project_role.created_at AS project_role_created_at, project_role.updated_at AS project_role_updated_at, project_role.deleted_at AS project_role_deleted_at, project_role.create_user AS project_role_create_user, project_role.update_user AS project_role_update_user 
FROM project_role 
WHERE project_role.user_id = %(user_id_1)s AND project_role.deleted_at IS NULL]
[parameters: {'user_id_1': 13}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2024-08-24 06:17:51.922890] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 06:18:09.978918] ERROR: UserDao: 查询用户：13项目失败，(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project_role.user_id' in 'field list'
[SQL: SELECT project_role.id AS project_role_id, project_role.user_id AS project_role_user_id, project_role.project_id AS project_role_project_id, project_role.project_role AS project_role_project_role, project_role.created_at AS project_role_created_at, project_role.updated_at AS project_role_updated_at, project_role.deleted_at AS project_role_deleted_at, project_role.create_user AS project_role_create_user, project_role.update_user AS project_role_update_user 
FROM project_role 
WHERE project_role.user_id = %(user_id_1)s AND project_role.deleted_at IS NULL]
[parameters: {'user_id_1': 13}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2024-08-24 06:18:09.979809] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 06:18:11.172910] ERROR: UserDao: 查询用户：13项目失败，(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project_role.user_id' in 'field list'
[SQL: SELECT project_role.id AS project_role_id, project_role.user_id AS project_role_user_id, project_role.project_id AS project_role_project_id, project_role.project_role AS project_role_project_role, project_role.created_at AS project_role_created_at, project_role.updated_at AS project_role_updated_at, project_role.deleted_at AS project_role_deleted_at, project_role.create_user AS project_role_create_user, project_role.update_user AS project_role_update_user 
FROM project_role 
WHERE project_role.user_id = %(user_id_1)s AND project_role.deleted_at IS NULL]
[parameters: {'user_id_1': 13}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2024-08-24 06:18:11.173289] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-24 06:40:26.812500] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:40:33.142224] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:40:34.224195] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:40:35.075718] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:40:35.737598] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:42:07.645059] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:42:59.479747] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:43:00.488885] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:43:02.157125] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:47:13.092244] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:47:13.945840] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 06:55:04.690923] ERROR: UserDao: 获取用户: 13项目列表失败, type object 'Project' has no attribute 'create_at'
[2024-08-24 07:01:31.081982] ERROR: UserDao: 获取用户: 13项目列表失败, paginate() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
[2024-08-24 18:34:08.927302] ERROR: UserDao: 查询用户：13项目失败，'NoneType' object is not iterable
[2024-08-24 18:34:08.931822] ERROR: UserDao: 获取用户: 13项目列表失败, exceptions must derive from BaseException
[2024-08-25 22:25:45.860994] ERROR: UserDao: 新增项目: sss失败, (builtins.TypeError) Not a boolean value: '测试'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'private': '测试', 'update_user': 14, 'create_user': 14, 'name': 'sss', 'created_at': datetime.datetime(2024, 8, 25, 22, 25, 45, 858374), 'description': True, 'owner': '14', 'updated_at': datetime.datetime(2024, 8, 25, 22, 25, 45, 858379), 'deleted_at': None}]]
[2024-08-25 22:25:51.086335] ERROR: UserDao: 新增项目: sss失败, (builtins.TypeError) Not a boolean value: '测试'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'private': '测试', 'update_user': 14, 'create_user': 14, 'name': 'sss', 'created_at': datetime.datetime(2024, 8, 25, 22, 25, 51, 85085), 'description': True, 'owner': '14', 'updated_at': datetime.datetime(2024, 8, 25, 22, 25, 51, 85093), 'deleted_at': None}]]
[2024-08-25 22:26:01.556613] ERROR: UserDao: 新增项目: 测试孙失败, (builtins.TypeError) Not a boolean value: '测试'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'private': '测试', 'update_user': 14, 'create_user': 14, 'name': '测试孙', 'created_at': datetime.datetime(2024, 8, 25, 22, 26, 1, 556084), 'description': True, 'owner': '14', 'updated_at': datetime.datetime(2024, 8, 25, 22, 26, 1, 556090), 'deleted_at': None}]]
[2024-08-25 22:28:04.722398] ERROR: UserDao: 新增项目: 测试孙失败, (builtins.TypeError) Not a boolean value: '测试'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'private': '测试', 'update_user': 14, 'create_user': 14, 'name': '测试孙', 'created_at': datetime.datetime(2024, 8, 25, 22, 28, 4, 721720), 'description': True, 'owner': '14', 'updated_at': datetime.datetime(2024, 8, 25, 22, 28, 4, 721727), 'deleted_at': None}]]
[2024-08-25 22:28:10.626309] ERROR: UserDao: 新增项目: 测试孙失败, (builtins.TypeError) Not a boolean value: '测试'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'private': '测试', 'update_user': 14, 'create_user': 14, 'name': '测试孙', 'created_at': datetime.datetime(2024, 8, 25, 22, 28, 10, 625594), 'description': True, 'owner': '14', 'updated_at': datetime.datetime(2024, 8, 25, 22, 28, 10, 625601), 'deleted_at': None}]]
[2024-08-25 22:28:14.914540] ERROR: UserDao: 新增项目: 测试孙失败, (builtins.TypeError) Not a boolean value: '测试'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'private': '测试', 'update_user': 14, 'create_user': 14, 'name': '测试孙', 'created_at': datetime.datetime(2024, 8, 25, 22, 28, 14, 913523), 'description': True, 'owner': '14', 'updated_at': datetime.datetime(2024, 8, 25, 22, 28, 14, 913529), 'deleted_at': None}]]
[2024-08-25 22:29:50.484431] ERROR: UserDao: 新增项目: 测试孙失败, (builtins.TypeError) Not a boolean value: '测试'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'private': '测试', 'update_user': 14, 'create_user': 14, 'name': '测试孙', 'created_at': datetime.datetime(2024, 8, 25, 22, 29, 50, 483711), 'description': True, 'owner': '14', 'updated_at': datetime.datetime(2024, 8, 25, 22, 29, 50, 483717), 'deleted_at': None}]]
[2024-08-25 22:47:35.497731] ERROR: UserDao: 新增项目: 测试孙失败, (builtins.TypeError) Not a boolean value: '测试'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'description': True, 'created_at': datetime.datetime(2024, 8, 25, 22, 42, 44, 985415), 'create_user': 14, 'update_user': 14, 'private': '测试', 'updated_at': datetime.datetime(2024, 8, 25, 22, 42, 45, 549714), 'name': '测试孙', 'owner': '14', 'deleted_at': None}]]
[2024-08-25 23:03:26.848097] ERROR: UserDao: 新增项目: 测试李失败, (builtins.TypeError) Not a boolean value: 'de'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'created_at': datetime.datetime(2024, 8, 25, 23, 2, 7, 443158), 'private': 'de', 'create_user': 14, 'name': '测试李', 'description': True, 'owner': '13', 'update_user': 14, 'updated_at': datetime.datetime(2024, 8, 25, 23, 2, 7, 693999), 'deleted_at': None}]]
[2024-08-25 23:06:08.607443] ERROR: UserDao: 新增项目: 测试李失败, (builtins.TypeError) Not a boolean value: 'de'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'created_at': datetime.datetime(2024, 8, 25, 23, 5, 56, 900932), 'private': 'de', 'create_user': 14, 'name': '测试李', 'description': True, 'owner': '13', 'update_user': 14, 'updated_at': datetime.datetime(2024, 8, 25, 23, 5, 57, 471894), 'deleted_at': None}]]
[2024-08-25 23:07:35.217432] ERROR: UserDao: 新增项目: 测试李失败, (builtins.TypeError) Not a boolean value: 'fed'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'created_at': datetime.datetime(2024, 8, 25, 23, 7, 31, 779550), 'description': True, 'owner': '13', 'name': '测试李', 'update_user': 14, 'private': 'fed', 'updated_at': datetime.datetime(2024, 8, 25, 23, 7, 31, 985135), 'create_user': 14, 'deleted_at': None}]]
[2024-08-25 23:08:54.849112] ERROR: UserDao: 新增项目: 测试李失败, (builtins.TypeError) Not a boolean value: 'fed'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'create_user': 14, 'updated_at': datetime.datetime(2024, 8, 25, 23, 8, 51, 501401), 'description': True, 'update_user': 14, 'owner': '13', 'private': 'fed', 'name': '测试李', 'created_at': datetime.datetime(2024, 8, 25, 23, 8, 51, 113904), 'deleted_at': None}]]
[2024-08-25 23:09:18.748828] ERROR: UserDao: 新增项目: 测试李失败, (builtins.TypeError) Not a boolean value: 'fed'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'create_user': 14, 'updated_at': datetime.datetime(2024, 8, 25, 23, 9, 14, 903683), 'description': True, 'update_user': 14, 'owner': '13', 'private': 'fed', 'name': '测试李', 'created_at': datetime.datetime(2024, 8, 25, 23, 9, 14, 700308), 'deleted_at': None}]]
[2024-08-25 23:16:02.821792] ERROR: UserDao: 新增项目: 悟空失败, (builtins.TypeError) Not a boolean value: '悟空'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'created_at': datetime.datetime(2024, 8, 25, 23, 15, 58, 286503), 'owner': '14', 'updated_at': datetime.datetime(2024, 8, 25, 23, 15, 58, 722576), 'description': True, 'update_user': 14, 'create_user': 14, 'private': '悟空', 'name': '悟空', 'deleted_at': None}]]
[2024-08-25 23:16:55.867373] ERROR: UserDao: 新增项目: 悟空失败, (builtins.TypeError) Not a boolean value: '悟空'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'owner': '14', 'update_user': 14, 'private': '悟空', 'create_user': 14, 'created_at': datetime.datetime(2024, 8, 25, 23, 16, 52, 520983), 'description': True, 'name': '悟空', 'updated_at': datetime.datetime(2024, 8, 25, 23, 16, 52, 702166), 'deleted_at': None}]]
[2024-08-26 20:42:01.358225] ERROR: UserDao: 查询项目：4角色列表失败,Entity '<class 'app.models.project_role.ProjectRole'>' has no property 'deleted'
[2024-08-26 20:42:21.228287] ERROR: UserDao: 查询项目：2角色列表失败,Entity '<class 'app.models.project_role.ProjectRole'>' has no property 'deleted'
[2024-08-26 20:55:37.862592] ERROR: UserDao: 查询项目: 2失败, Entity '<class 'app.models.project.Project'>' has no property 'delete_at'
[2024-08-26 20:58:10.341416] ERROR: UserDao: 查询项目：2角色列表失败,Entity '<class 'app.models.project_role.ProjectRole'>' has no property 'deleted'
[2024-08-26 20:58:41.092725] ERROR: UserDao: 查询项目：2角色列表失败,Entity '<class 'app.models.project_role.ProjectRole'>' has no property 'deleted'
[2024-08-27 06:39:07.487463] ERROR: UserDao: 添加项目用户失败, name 'user_role' is not defined
[2024-08-27 06:39:11.460749] ERROR: UserDao: 添加项目用户失败, name 'user_role' is not defined
[2024-08-27 06:39:15.165577] ERROR: UserDao: 添加项目用户失败, name 'user_role' is not defined
[2024-08-27 06:39:15.570983] ERROR: UserDao: 添加项目用户失败, name 'user_role' is not defined
[2024-08-29 07:51:15.751509] ERROR: UserDao: 新增项目: 帝国神话2失败, (builtins.TypeError) Not a boolean value: '4'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'description': False, 'updated_at': datetime.datetime(2024, 8, 29, 7, 51, 15, 748778), 'owner': '21', 'name': '帝国神话2', 'created_at': datetime.datetime(2024, 8, 29, 7, 51, 15, 748768), 'update_user': 21, 'private': '4', 'create_user': 21, 'deleted_at': None}]]
[2024-08-29 07:51:21.526987] ERROR: UserDao: 新增项目: 帝国神话2失败, (builtins.TypeError) Not a boolean value: '4'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'description': True, 'updated_at': datetime.datetime(2024, 8, 29, 7, 51, 21, 526295), 'owner': '21', 'name': '帝国神话2', 'created_at': datetime.datetime(2024, 8, 29, 7, 51, 21, 526288), 'update_user': 21, 'private': '4', 'create_user': 21, 'deleted_at': None}]]
[2024-08-29 07:52:04.937387] ERROR: UserDao: 新增项目: 帝国神话2失败, (builtins.TypeError) Not a boolean value: '4'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'description': True, 'updated_at': datetime.datetime(2024, 8, 29, 7, 52, 4, 936635), 'owner': '21', 'name': '帝国神话2', 'created_at': datetime.datetime(2024, 8, 29, 7, 52, 4, 936629), 'update_user': 21, 'private': '4', 'create_user': 21, 'deleted_at': None}]]
[2024-08-29 07:52:36.421085] ERROR: UserDao: 新增项目: 帝国失败, (builtins.TypeError) Not a boolean value: '4'
[SQL: INSERT INTO project (name, owner, created_at, updated_at, deleted_at, create_user, update_user, private, description) VALUES (%(name)s, %(owner)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(private)s, %(description)s)]
[parameters: [{'description': True, 'updated_at': datetime.datetime(2024, 8, 29, 7, 52, 36, 420412), 'owner': '21', 'name': '帝国', 'created_at': datetime.datetime(2024, 8, 29, 7, 52, 36, 420406), 'update_user': 21, 'private': '4', 'create_user': 21, 'deleted_at': None}]]
[2024-09-02 19:30:00.565608] ERROR: UserDao: 获取测试用例失败: (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'test_case.params' in 'field list'
[SQL: SELECT test_case.id AS test_case_id, test_case.name AS test_case_name, test_case.request_type AS test_case_request_type, test_case.url AS test_case_url, test_case.request_method AS test_case_request_method, test_case.request_header AS test_case_request_header, test_case.params AS test_case_params, test_case.body AS test_case_body, test_case.project_id AS test_case_project_id, test_case.tag AS test_case_tag, test_case.status AS test_case_status, test_case.priority AS test_case_priority, test_case.catalogue AS test_case_catalogue, test_case.expected AS test_case_expected, test_case.created_at AS test_case_created_at, test_case.updated_at AS test_case_updated_at, test_case.deleted_at AS test_case_deleted_at, test_case.create_user AS test_case_create_user, test_case.update_user AS test_case_update_user 
FROM test_case 
WHERE test_case.project_id = %(project_id_1)s AND test_case.deleted_at IS NULL ORDER BY test_case.name ASC]
[parameters: {'project_id_1': '25'}]
(Background on this error at: http://sqlalche.me/e/f405)
[2024-09-02 19:32:09.875207] ERROR: UserDao: 获取测试用例失败: (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'test_case.params' in 'field list'
[SQL: SELECT test_case.id AS test_case_id, test_case.name AS test_case_name, test_case.request_type AS test_case_request_type, test_case.url AS test_case_url, test_case.request_method AS test_case_request_method, test_case.request_header AS test_case_request_header, test_case.params AS test_case_params, test_case.body AS test_case_body, test_case.project_id AS test_case_project_id, test_case.tag AS test_case_tag, test_case.status AS test_case_status, test_case.priority AS test_case_priority, test_case.catalogue AS test_case_catalogue, test_case.expected AS test_case_expected, test_case.created_at AS test_case_created_at, test_case.updated_at AS test_case_updated_at, test_case.deleted_at AS test_case_deleted_at, test_case.create_user AS test_case_create_user, test_case.update_user AS test_case_update_user 
FROM test_case 
WHERE test_case.project_id = %(project_id_1)s AND test_case.deleted_at IS NULL ORDER BY test_case.name ASC]
[parameters: {'project_id_1': '25'}]
(Background on this error at: http://sqlalche.me/e/f405)
[2024-09-02 19:33:43.532568] ERROR: UserDao: 获取测试用例失败: (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'test_case.params' in 'field list'
[SQL: SELECT test_case.id AS test_case_id, test_case.name AS test_case_name, test_case.request_type AS test_case_request_type, test_case.url AS test_case_url, test_case.request_method AS test_case_request_method, test_case.request_header AS test_case_request_header, test_case.params AS test_case_params, test_case.body AS test_case_body, test_case.project_id AS test_case_project_id, test_case.tag AS test_case_tag, test_case.status AS test_case_status, test_case.priority AS test_case_priority, test_case.catalogue AS test_case_catalogue, test_case.expected AS test_case_expected, test_case.created_at AS test_case_created_at, test_case.updated_at AS test_case_updated_at, test_case.deleted_at AS test_case_deleted_at, test_case.create_user AS test_case_create_user, test_case.update_user AS test_case_update_user 
FROM test_case 
WHERE test_case.project_id = %(project_id_1)s AND test_case.deleted_at IS NULL ORDER BY test_case.name ASC]
[parameters: {'project_id_1': '25'}]
(Background on this error at: http://sqlalche.me/e/f405)
[2024-09-02 19:33:53.872844] ERROR: UserDao: 获取测试用例失败: (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'test_case.params' in 'field list'
[SQL: SELECT test_case.id AS test_case_id, test_case.name AS test_case_name, test_case.request_type AS test_case_request_type, test_case.url AS test_case_url, test_case.request_method AS test_case_request_method, test_case.request_header AS test_case_request_header, test_case.params AS test_case_params, test_case.body AS test_case_body, test_case.project_id AS test_case_project_id, test_case.tag AS test_case_tag, test_case.status AS test_case_status, test_case.priority AS test_case_priority, test_case.catalogue AS test_case_catalogue, test_case.expected AS test_case_expected, test_case.created_at AS test_case_created_at, test_case.updated_at AS test_case_updated_at, test_case.deleted_at AS test_case_deleted_at, test_case.create_user AS test_case_create_user, test_case.update_user AS test_case_update_user 
FROM test_case 
WHERE test_case.project_id = %(project_id_1)s AND test_case.deleted_at IS NULL ORDER BY test_case.name ASC]
[parameters: {'project_id_1': '23'}]
(Background on this error at: http://sqlalche.me/e/f405)
[2024-09-02 19:34:09.397944] ERROR: UserDao: 获取测试用例失败: (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'test_case.params' in 'field list'
[SQL: SELECT test_case.id AS test_case_id, test_case.name AS test_case_name, test_case.request_type AS test_case_request_type, test_case.url AS test_case_url, test_case.request_method AS test_case_request_method, test_case.request_header AS test_case_request_header, test_case.params AS test_case_params, test_case.body AS test_case_body, test_case.project_id AS test_case_project_id, test_case.tag AS test_case_tag, test_case.status AS test_case_status, test_case.priority AS test_case_priority, test_case.catalogue AS test_case_catalogue, test_case.expected AS test_case_expected, test_case.created_at AS test_case_created_at, test_case.updated_at AS test_case_updated_at, test_case.deleted_at AS test_case_deleted_at, test_case.create_user AS test_case_create_user, test_case.update_user AS test_case_update_user 
FROM test_case 
WHERE test_case.project_id = %(project_id_1)s AND test_case.deleted_at IS NULL ORDER BY test_case.name ASC]
[parameters: {'project_id_1': '23'}]
(Background on this error at: http://sqlalche.me/e/f405)
[2024-09-02 19:34:20.336840] ERROR: UserDao: 获取测试用例失败: (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'test_case.params' in 'field list'
[SQL: SELECT test_case.id AS test_case_id, test_case.name AS test_case_name, test_case.request_type AS test_case_request_type, test_case.url AS test_case_url, test_case.request_method AS test_case_request_method, test_case.request_header AS test_case_request_header, test_case.params AS test_case_params, test_case.body AS test_case_body, test_case.project_id AS test_case_project_id, test_case.tag AS test_case_tag, test_case.status AS test_case_status, test_case.priority AS test_case_priority, test_case.catalogue AS test_case_catalogue, test_case.expected AS test_case_expected, test_case.created_at AS test_case_created_at, test_case.updated_at AS test_case_updated_at, test_case.deleted_at AS test_case_deleted_at, test_case.create_user AS test_case_create_user, test_case.update_user AS test_case_update_user 
FROM test_case 
WHERE test_case.project_id = %(project_id_1)s AND test_case.deleted_at IS NULL ORDER BY test_case.name ASC]
[parameters: {'project_id_1': '23'}]
(Background on this error at: http://sqlalche.me/e/f405)
